kind: pipeline
type: docker
name: minecraft-box

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: mtimoustafa/minecraft-box
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_COMMIT_BRANCH}
    when:
      event: push

  - name: deploy
    image: amazon/aws-cli
    commands:
      - ./build.sh
      settings:
        environment:
          AWS_ACCESS_KEY_ID:
            from_secret: aws_access_key_id
          AWS_SECRET_ACCESS_KEY:
            from_secret: aws_secret_access_key
    when:
      branch: master
      event: push
