pipeline:
  build:
    image: plugins/docker
    repo: mtimoustafa/minecraft-box
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - ${DRONE_COMMIT_BRANCH}
    when:
      event: push

  deploy:
    image: amazon/aws-cli
    commands:
      - ./build.sh
    when:
      branch: master
      event: push
