pipeline:
  build:
    image: plugins/docker
    repo: mtimoustafa/minecraft-box
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - ${DRONE_COMMIT_BRANCH}
    when:
      event: push

  deploy:
    image: peloton/drone-ecs
    service: minecraft-box-service
    family: minecraft-box-task
    image_name: mtimoustafa/minecraft-box
    image_tag: master
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    when:
      branch: master
      event: push
