pipeline:
  build:
    image: plugins/docker
    repo: mtimoustafa/minecraft-box
    secrets: [ docker_username, docker_password ]
    tags: ${DRONE_COMMIT_BRANCH}

  build_latest:
    image: plugins/docker
    repo: mtimoustafa/minecraft-box
    secrets: [ docker_username, docker_password ]
    tags: latest
    when:
      branch:
        - master
