pipeline:
  build:
    image: plugins/docker
    repo: mtimoustafa/minecraft-box
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: ${DRONE_COMMIT_BRANCH}

branches: !(master)

---
pipeline:
  build_latest:
    image: plugins/docker
    repo: mtimoustafa/minecraft-box
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

branches: master
