kind: pipeline
type: docker
name: minecraft-box

steps:
- name: build
  image: plugins/docker
  settings:
    repo: mtimoustafa/minecraft-box
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_BRANCH}

- name: build_latest
  image: plugins/docker
  settings:
    repo: mtimoustafa/minecraft-box
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
    when:
      branch:
        - master
