kind: pipeline
type: docker
name: minecraft-box

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: mtimoustafa/minecraft-box
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_COMMIT_BRANCH}
    when:
      event: push
